version: '2'
services:
  api:
    build: ./api
    ports:
     - "8080:8080"
    links:
      - db:db
    volumes:
      - .:/example-volume
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
  db:
    build: ./database
    

